### ISSUE TITLE
rc9 does not start up when using mounted HPSS

### ISSUE THREAD

**Issue by bwegh** [indigo-dc/onedata#6]
the issue could be caused by permissions or similar, yet I do not find anything helpful in the error/logs

[oneprovider_20161012_112844.zip](https://github.com/indigo-dc/onedata/files/523907/oneprovider_20161012_112844.zip)

**Comment by bwegh** [comment]
we updated the nfs mount of hpss, yet still no luck

[oneprovider_20161014_115303.zip](https://github.com/indigo-dc/onedata/files/529063/oneprovider_20161014_115303.zip)

**Comment by groundnuty** [comment]
they do not tell us much, I think that without access to the VM there is little we can do

**Comment by marcvs** [comment]
We have a specific backend. It only allows to write files either as root or in the UIDs of 10.000.000 - 11.000.000. (Same for GIDs)

If you write (or chown) outside this range it will result in an error.

Question is, which UIDs you're using.

I don't think locking is an issue.

**Comment by groundnuty** [comment]
@marcvs you are in luck, as we do provider such functionality since early days of the project :)
however, it's the first time it is requested since we switched to docker, so one needs to make an extra effort to make it work.

The file you are interested in can be found in Oneprovider in docker container in:
/volumes/persistence/var/lib/op_worker/auth.config

This file contains entries such as:

```
      {lowest_generated_storage_uid,100000},
      {highest_generated_storage_uid,2000000},
```

which represent the range from which a uid and gid (the settings name is unfortunate) that can be assigned for a user and a group.

Please look at getting-started repo, branch beta.onedata.org. These are our official configuration files that we use to deploy environments at this domain. The example is for Onezone, but the principle for Oneprovider remains the same. 

https://github.com/onedata/getting-started/blob/beta.onedata.org/scenarios/0_0_onedata_org/docker-compose-onezone.yml

as seen here, you store the app.config file next to certificates on your host system and mount it as a volume into the container. For Oneprovider the exact config lien would be:
- "< path to your app.config >:/volumes/persistence/var/lib/op_worker/app.config"

I hope it helps,
Michal

**Comment by bwegh** [comment]
looks a bit confusing to me:
it is in the docker at:

```
/volumes/persistence/etc/op_worker/app.config
```

but should be mounted in the volumes section as

```
/volumes/persistence/var/lib/op_worker/auth.config
```

is this correct?
can you please provide a sample file?
as "contains entries like" sound a bit vague to me.

**Comment by groundnuty** [comment]
auth.config is for open id configuration etc.
app.config - has various parameters for Onedata services, only subset of them is exposed in docker-compose

I edited my previous comment, realising I wrote auth instead of app. 

Clear now? Happy to clarify more.

**Comment by bwegh** [comment]
no, as the whole path is different, please see above, once it is in `/var` and once in `/etc`.

Also please provide a default `app.config` to adjust, thanks

**Comment by bwegh** [comment]
still no luck, tried both mount points:

```
/volumes/persistence/etc/op_worker/app.config
```

and 

```
volumes/persistence/var/lib/op_worker/app.config
```

could you please let me know, which one is correct?

results are attached
[oneprovider_20161026_111140.zip](https://github.com/indigo-dc/onedata/files/552678/oneprovider_20161026_111140.zip)

**Comment by groundnuty** [comment]
@bwegh 
seems that you are mounting it correctly, but there is an error in parsing the file
please attach your app.config.

**Comment by bwegh** [comment]
is in the zip file attached above, in the script.log

**Comment by bwegh** [comment]
is in the zip file attached above, in the script.log

**Comment by bwegh** [comment]
is in the zip file attached above, in the script.log

**Comment by bwegh** [comment]
is in the zip file attached above, in the script.log

**Comment by groundnuty** [comment]
you are missing the '.' at the end. Comparing your app.conf with the original shows:

```
129c130
<       {ctool,[{verify_oz_cert,false}]}]
---
>  {ctool,[{verify_oz_cert,false}]}].
```

it's erlang :(

**Comment by bwegh** [comment]
still no luck ... 
[latest.zip](https://github.com/indigo-dc/onedata/files/577654/latest.zip)

**Comment by groundnuty** [comment]
The log says that:
1) app.config is ok
2) the simple write/read test on one of the storages failed. 

I think that, the only thing we can do at this point is to investivate by accessing the machine :(

**Comment by groundnuty** [comment]
Did it work? I would like to possible close this issue.

**Comment by bwegh** [comment]
did not further test, will go on with RC11 and might open a new ticket, if needed
