### ISSUE TITLE
oneprovider admin interface: does not show total amount of space and used space

### ISSUE THREAD

**Issue by mariojmdavid** [indigo-dc/onedata#8]
I know how much is the total storage in a oneprovider space, but this is not shown in the admin web interface

as we add spaces to users there should be shown the amount of storage of each user space, and as well as the amount still free to give for new user spaces

**Comment by groundnuty** [comment]
@mariojmdavid 
we discussed this thing and came to a conclusion that at this stage we don't want to tie the total sum of storage of supported spaces with the capacity of provider storage. The storage can be extended dynamically after all.

W propose to introduce the setting in onepanel (oneprovider gui) 'total storage' (maybe better name), that admin will be able to edit (and supply pre-defined value via docker-comose config). Then we cloud show the value of 'total storage'-sum(all_spaces_capacities) in the GUI. 

Also we will provider the REST call with which you will be able to ask provider how much space he provides and maybe a REST call about free space. It will make it very simple to write a script that will monitor lets say... how much space is left in providers connected to onedata.indigo-datacloud.eu.

Feel free to comment.

**Comment by groundnuty** [comment]
As of next version, it will. I've managed to push this feature through!

**Comment by kliput** [comment]
Hello,

Showing storage total support size, spaces support and total space support size is almost done. It should be included in our next release.

Screenshots:
![image](https://user-images.githubusercontent.com/1345438/29673675-3c1012b2-88f0-11e7-9db3-49497a40fa0f.png)
![image](https://user-images.githubusercontent.com/1345438/29673819-9bcc533c-88f0-11e7-86ad-06eda4a12bbc.png)

Note, that currently on space support chart, name of provider will be presented only for provider local to Onepanel. It's due to panel authorization limitations.

**Comment by kliput** [comment]
Merged into develop, will be included in next release.

Also, a new design of the chart is on the way (in development):
![image](https://user-images.githubusercontent.com/1345438/29964144-6bcd0630-8f09-11e7-8fa8-9e153d392baf.png)
